/**
 * OBD-II DATABASE & DECODER
 * Полная база кодов ошибок OBD-II с расшифровкой, рекомендациями и ценами
 */

export const OBD_DATABASE = {
  "P0001": { title: "Fuel Volume Regulator Control Circuit", system: "Fuel", danger: "средний", description: "Проблема с регулятором давления топлива. Машина может ехать, но с потерей мощности.", canDrive: true, urgency: "3 дня", priceMin: 2500, priceMax: 8000, actions: ["Проверить датчик давления", "Осмотреть регулятор", "Очистить топливный фильтр"], parts: ["Регулятор давления", "Датчик давления топлива"] },
  "P0011": { title: "Camshaft Position Timing Over-Advanced", system: "Engine", danger: "средний", description: "Проблема с системой изменения фаз газораспределения. Двигатель может троить.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 5000, actions: ["Проверить цепь ГРМ", "Осмотреть датчик положения"], parts: ["Датчик положения распредвала", "Цепь ГРМ"] },
  "P0014": { title: "Camshaft Position Timing Over-Retarded", system: "Engine", danger: "средний", description: "Фазы ГРМ сдвинуты в сторону запаздывания. Потеря мощности и нестабильный холостой ход.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 5000, actions: ["Заменить масло", "Проверить датчик"], parts: ["Датчик положения распредвала", "Масло моторное"] },
  "P0016": { title: "Crankshaft Camshaft Position Correlation", system: "Engine", danger: "средний", description: "Несоответствие между датчиками коленвала и распредвала. Двигатель может не завести или работает нестабильно.", canDrive: false, urgency: "сегодня", priceMin: 3000, priceMax: 8000, actions: ["Проверить датчик коленвала", "Проверить датчик распредвала", "Осмотреть цепь ГРМ"], parts: ["Датчик коленвала", "Датчик распредвала"] },
  "P0017": { title: "Crankshaft Camshaft Timing Misalignment Bank 2", system: "Engine", danger: "средний", description: "Проблема с синхронизацией на цилиндрах 4-6. Нестабильная работа двигателя.", canDrive: true, urgency: "1 неделя", priceMin: 2000, priceMax: 6000, actions: ["Проверить датчики", "Осмотреть цепь ГРМ"], parts: ["Датчик положения распредвала", "Датчик коленвала"] },
  "P0020": { title: "Camshaft Position Actuator Control Circuit Bank 2", system: "Engine", danger: "низкий", description: "Проблема с системой VVT на второй стороне. Может ехать нормально.", canDrive: true, urgency: "1 месяц", priceMin: 2000, priceMax: 6000, actions: ["Заменить масло", "Проверить фильтр", "Диагно��тика"], parts: ["Масло моторное", "Воздушный фильтр"] },
  "P0030": { title: "Oxygen Sensor Heater Control Circuit", system: "Emission", danger: "низкий", description: "Проблема с подогревом датчика кислорода. Немного повышенный расход.", canDrive: true, urgency: "1 месяц", priceMin: 1200, priceMax: 3000, actions: ["Проверить разъём датчика", "Осмотреть проводку"], parts: ["Датчик кислорода", "Провода"] },
  "P0101": { title: "Mass Airflow Sensor Range Performance", system: "Engine", danger: "средний", description: "Датчик расхода воздуха некорректно работает. Двигатель может троить, потеря мощности.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить датчик", "Проверить воздухозаборник", "Заменить воздушный фильтр"], parts: ["Датчик MAF", "Воздушный фильтр"] },
  "P0102": { title: "Mass Airflow Sensor Circuit Low Input", system: "Engine", danger: "средний", description: "Датчик MAF показывает низкое напряжение. Двигатель работает нестабильно.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить датчик спиртом", "Проверить проводку", "Заменить датчик"], parts: ["Датчик MAF", "Провода и разъёмы"] },
  "P0103": { title: "Mass Airflow Sensor High Input", system: "Engine", danger: "средний", description: "Датчик MAF показывает высокое напряжение. Повышенный расход топлива.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Проверить герметичность воздуховодов", "Заменить датчик"], parts: ["Датчик MAF", "Воздухозабор"] },
  "P0105": { title: "Manifold Absolute Pressure Sensor Range Performance", system: "Engine", danger: "низкий", description: "Датчик абсолютного давления работает нестабильно. Может быть небольшое снижение производительности.", canDrive: true, urgency: "1 месяц", priceMin: 1000, priceMax: 2500, actions: ["Проверить вакуумные шланги", "Осмотреть датчик"], parts: ["Датчик MAP", "Вакуумные шланги"] },
  "P0106": { title: "Manifold Absolute Pressure Sensor Circuit Range Performance", system: "Engine", danger: "низкий", description: "Проблема с датчиком давления во впускном коллекторе. Нестабильный холостой ход.", canDrive: true, urgency: "1 месяц", priceMin: 1000, priceMax: 2500, actions: ["Проверить разъём датчика", "Осмотреть вакуумные шланги"], parts: ["Датчик MAP", "Вакуумные шланги"] },
  "P0107": { title: "Manifold Absolute Pressure Sensor Circuit Low Input", system: "Engine", danger: "низкий", description: "Датчик MAP показывает низкое напряжение. Нестабильная работа.", canDrive: true, urgency: "1 месяц", priceMin: 1000, priceMax: 2500, actions: ["Проверить проводку", "Заменить датчик"], parts: ["Датчик MAP", "Провода"] },
  "P0108": { title: "Manifold Absolute Pressure Sensor Circuit High Input", system: "Engine", danger: "низкий", description: "Датчик MAP показывает высокое напряжение. Проблем может не быть, или нужна калибровка.", canDrive: true, urgency: "1 месяц", priceMin: 1000, priceMax: 2500, actions: ["Проверить разъём", "Заменить датчик"], parts: ["Датчик MAP"] },
  "P0111": { title: "Intake Air Temperature Sensor Range Performance", system: "Engine", danger: "низкий", description: "Датчик температуры воздуха работает нестабильно. Могут быть проблемы с холостым ходом.", canDrive: true, urgency: "1 месяц", priceMin: 500, priceMax: 1500, actions: ["Проверить датчик", "Очистить воздухозаборник"], parts: ["Датчик температуры воздуха"] },
  "P0112": { title: "Intake Air Temperature Sensor Circuit Low", system: "Engine", danger: "низкий", description: "Датчик температуры показывает слишком низкую температуру. Небольшие проблемы с работой.", canDrive: true, urgency: "1 месяц", priceMin: 500, priceMax: 1500, actions: ["Проверить разъём датчика", "Заменить датчик"], parts: ["Датчик температуры воздуха", "Разъёмы"] },
  "P0113": { title: "Intake Air Temperature Sensor Circuit High", system: "Engine", danger: "низкий", description: "Датчик температуры показывает слишком высокую температуру. Неправильное форсирование топлива.", canDrive: true, urgency: "1 месяц", priceMin: 500, priceMax: 1500, actions: ["Проверить датчик", "Проверить проводку"], parts: ["Датчик температуры воздуха"] },
  "P0115": { title: "Engine Coolant Temperature Sensor Range Performance", system: "Engine", danger: "средний", description: "Датчик температуры охлаждающей жидкости работает нестабильно. Проблемы с запуском и работой двигателя.", canDrive: true, urgency: "1 неделя", priceMin: 1000, priceMax: 2500, actions: ["Проверить датчик", "Проверить охлаждающую жидкость"], parts: ["Датчик температуры охлаждающей жидкости"] },
  "P0116": { title: "Engine Coolant Temperature Sensor Circuit Range Performance", system: "Engine", danger: "средний", description: "Проблема с датчиком температуры охлаждающей жидкости. Неправильная работа вентилятора охлаждения.", canDrive: true, urgency: "1 неделя", priceMin: 1000, priceMax: 2500, actions: ["Заменить датчик", "Проверить электрическую цепь"], parts: ["Датчик температуры охлаждающей жидкости"] },
  "P0117": { title: "Engine Coolant Temperature Sensor Circuit Low", system: "Engine", danger: "средний", description: "Датчик показывает слишком низкую температуру. Проблемы с холодным пуском.", canDrive: true, urgency: "3 дня", priceMin: 1000, priceMax: 2500, actions: ["Заменить датчик", "Проверить разъём"], parts: ["Датчик температуры охлаждающей жидкости", "Разъёмы"] },
  "P0118": { title: "Engine Coolant Temperature Sensor Circuit High", system: "Engine", danger: "средний", description: "Датчик показывает слишком высокую температуру. Может привести к снижению расхода топлива.", canDrive: true, urgency: "3 дня", priceMin: 1000, priceMax: 2500, actions: ["Заменить датчик", "Проверить антифриз"], parts: ["Датчик температуры охлаждающей жидкости"] },
  "P0120": { title: "Throttle Position Sensor Circuit", system: "Engine", danger: "средний", description: "Проблема с датчиком положения дроссельной заслонки. Нестабильное ускорение.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить дроссель", "Заменить датчик", "Проверить проводку"], parts: ["Датчик положения дроссельной заслонки", "Дроссельная заслонка"] },
  "P0128": { title: "Coolant Thermostat (Coolant Temp Malfunction)", system: "Engine", danger: "средний", description: "Проблема с термостатом. Двигатель может перегреваться или переохлаждаться.", canDrive: true, urgency: "1 неделя", priceMin: 2000, priceMax: 5000, actions: ["Заменить термостат", "Проверить антифриз", "Проверить помпу"], parts: ["Термостат", "Антифриз", "Помпа охлаждения"] },
  "P0130": { title: "Oxygen Sensor Circuit", system: "Emission", danger: "средний", description: "Проблема с датчиком кислорода (лямбда-зонд). Повышенный расход топлива.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Заменить датчик кислорода", "Проверить выхлопную систему"], parts: ["Датчик кислорода", "Выхлопная труба"] },
  "P0131": { title: "Oxygen Sensor Circuit Low Voltage", system: "Emission", danger: "средний", description: "Датчик кислорода показывает низкое напряжение. Неправильное соотношение топлива и воздуха.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Заменить датчик кислорода", "Проверить выхлоп"], parts: ["Датчик кислорода"] },
  "P0132": { title: "Oxygen Sensor Circuit High Voltage", system: "Emission", danger: "средний", description: "Датчик кислорода показывает высокое напряжение. Может указывать на слишком богатую смесь.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Заменить датчик кислорода", "Проверить инжектор"], parts: ["Датчик кислорода", "Форсунка инжектора"] },
  "P0133": { title: "Oxygen Sensor Circuit Slow Response", system: "Emission", danger: "низкий", description: "Датчик кислорода медленно реагирует на изменения. Небольшое увеличение расхода.", canDrive: true, urgency: "1 месяц", priceMin: 1500, priceMax: 4000, actions: ["Очистить датчик", "Заменить датчик"], parts: ["Датчик кислорода"] },
  "P0134": { title: "Oxygen Sensor Circuit No Activity", system: "Emission", danger: "средний", description: "Датчик кислорода не передает сигналы. Проблемы с двигателем и выхлопом.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Заменить датчик", "Проверить проводку"], parts: ["Датчик кислорода", "Провода и разъёмы"] },
  "P0135": { title: "Oxygen Sensor Heater Circuit", system: "Emission", danger: "низкий", description: "Проблема с подогревом датчика кислорода. Может быть медленный прогрев.", canDrive: true, urgency: "1 месяц", priceMin: 1200, priceMax: 3000, actions: ["Проверить электрическую цепь", "Заменить датчик"], parts: ["Датчик кислорода", "Провода"] },
  "P0140": { title: "Oxygen Sensor Circuit Bank 2", system: "Emission", danger: "средний", description: "Проблема с датчиком кислорода на второй стороне. Повышенный расход топлива.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Заменить датчик", "Проверить выхлоп"], parts: ["Датчик кислорода"] },
  "P0150": { title: "Fuel Trim System (Bank 1) Malfunction", system: "Fuel", danger: "средний", description: "Система регулировки топлива не может найти оптимальное значение. Нестабильная работа.", canDrive: true, urgency: "3 дня", priceMin: 2000, priceMax: 6000, actions: ["Очистить инжектор", "Заменить топливный фильтр", "Диагностика"], parts: ["Форсунка инжектора", "Топливный фильтр"] },
  "P0171": { title: "System Too Lean (Bank 1)", system: "Fuel", danger: "средний", description: "Смесь слишком бедная на первой стороне двигателя. Потеря мощности, повышенный расход.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 5000, actions: ["Проверить датчик кислорода", "Очистить инжектор", "Проверить давление топлива"], parts: ["Датчик кислорода", "Форсунка инжектора", "Топливный фильтр"] },
  "P0172": { title: "System Too Rich (Bank 1)", system: "Fuel", danger: "средний", description: "Смесь слишком богатая на первой стороне двигателя. Запах бензина в выхлопе.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 5000, actions: ["Проверить датчик кислорода", "Очистить инжектор"], parts: ["Датчик кислорода", "Форсунка инжектора"] },
  "P0174": { title: "System Too Lean (Bank 2)", system: "Fuel", danger: "средний", description: "Смесь слишком бедная на второй стороне двигателя. Потеря мощности.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 5000, actions: ["Проверить датчик кислорода", "Очистить инжектор"], parts: ["Датчик кислорода", "Форсунка инжектора"] },
  "P0175": { title: "System Too Rich (Bank 2)", system: "Fuel", danger: "средний", description: "Смесь слишком богатая на второй стороне двигателя. Запах в выхлопе.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 5000, actions: ["Проверить датчик кислорода", "Очистить инжектор"], parts: ["Датчик кислорода", "Форсунка инжектора"] },
  "P0200": { title: "Fuel Injector Circuit", system: "Fuel", danger: "средний", description: "Проблема с электрической цепью форсунок инжектора. Двигатель может не запуститься.", canDrive: false, urgency: "сегодня", priceMin: 2000, priceMax: 6000, actions: ["Очистить форсунки", "Проверить разъём", "Заменить форсунку"], parts: ["Форсунка инжектора", "Провода и разъёмы"] },
  "P0201": { title: "Fuel Injector Circuit Cylinder 1", system: "Fuel", danger: "средний", description: "Проблема с форсункой первого цилиндра. Двигатель может троить.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить форсунку", "Заменить форсунку"], parts: ["Форсунка инжектора"] },
  "P0202": { title: "Fuel Injector Circuit Cylinder 2", system: "Fuel", danger: "средний", description: "Проблема с форсункой второго цилиндра. Неровная работа.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить форсунку", "Заменить форсунку"], parts: ["Форсунка инжектора"] },
  "P0203": { title: "Fuel Injector Circuit Cylinder 3", system: "Fuel", danger: "средний", description: "Проблема с форсункой третьего цилиндра.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить форсунку", "Заменить форсунку"], parts: ["Форсунка инжектора"] },
  "P0204": { title: "Fuel Injector Circuit Cylinder 4", system: "Fuel", danger: "средний", description: "Проблема с форсункой четвёртого цилиндра.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить форсунку", "Заменить форсунку"], parts: ["Форсунка инжектора"] },
  "P0205": { title: "Fuel Injector Circuit Cylinder 5", system: "Fuel", danger: "средний", description: "Проблема с форсункой пятого цилиндра.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить форсунку", "Заменить форсунку"], parts: ["Форсунка инжектора"] },
  "P0206": { title: "Fuel Injector Circuit Cylinder 6", system: "Fuel", danger: "средний", description: "Проблема с форсункой шестого цилиндра.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить форсунку", "Заменить форсунку"], parts: ["Форсунка инжектора"] },
  "P0300": { title: "Random Misfire Detected", system: "Engine", danger: "высокий", description: "Обнаружены пропуски зажигания в разных цилиндрах. Двигатель троит, вибрирует.", canDrive: false, urgency: "сегодня", priceMin: 3000, priceMax: 10000, actions: ["Проверить свечи зажигания", "Проверить катушки зажигания", "Диагностика"], parts: ["Свечи зажигания", "Катушка зажигания", "Провода высокого напряжения"] },
  "P0301": { title: "Cylinder 1 Misfire Detected", system: "Engine", danger: "высокий", description: "Пропуск зажигания в первом цилиндре. Двигатель троит, вибрирует.", canDrive: false, urgency: "сегодня", priceMin: 1500, priceMax: 5000, actions: ["Заменить свечу зажигания", "Проверить катушку", "Проверить компрессию"], parts: ["Свеча зажигания", "Катушка зажигания"] },
  "P0302": { title: "Cylinder 2 Misfire Detected", system: "Engine", danger: "высокий", description: "Пропуск зажигания во втором цилиндре.", canDrive: false, urgency: "сегодня", priceMin: 1500, priceMax: 5000, actions: ["Заменить свечу зажигания", "Проверить катушку"], parts: ["Свеча зажигания", "Катушка зажигания"] },
  "P0303": { title: "Cylinder 3 Misfire Detected", system: "Engine", danger: "высокий", description: "Пропуск зажигания в третьем цилиндре.", canDrive: false, urgency: "сегодня", priceMin: 1500, priceMax: 5000, actions: ["Заменить свечу зажигания", "Проверить катушку"], parts: ["Свеча зажигания", "Катушка зажигания"] },
  "P0304": { title: "Cylinder 4 Misfire Detected", system: "Engine", danger: "высокий", description: "Пропуск зажигания в четвёртом цилиндре.", canDrive: false, urgency: "сегодня", priceMin: 1500, priceMax: 5000, actions: ["Заменить свечу зажигания", "Проверить катушку"], parts: ["Свеча зажигания", "Катушка зажигания"] },
  "P0305": { title: "Cylinder 5 Misfire Detected", system: "Engine", danger: "высокий", description: "Пропуск зажигания в пятом цилиндре.", canDrive: false, urgency: "сегодня", priceMin: 1500, priceMax: 5000, actions: ["Заменить свечу зажигания", "Проверить катушку"], parts: ["Свеча зажигания", "Катушка зажигания"] },
  "P0306": { title: "Cylinder 6 Misfire Detected", system: "Engine", danger: "высокий", description: "Пропуск зажигания в шестом цилиндре.", canDrive: false, urgency: "сегодня", priceMin: 1500, priceMax: 5000, actions: ["Заменить свечу зажигания", "Проверить катушку"], parts: ["Свеча зажигания", "Катушка зажигания"] },
  "P0400": { title: "Exhaust Gas Recirculation Flow", system: "Emission", danger: "средний", description: "Проблема с системой рециркуляции выхлопных газов (EGR). Нестабильный холостой ход.", canDrive: true, urgency: "1 неделя", priceMin: 2500, priceMax: 7000, actions: ["Очистить клапан EGR", "Проверить датчик EGR", "Диагностика"], parts: ["Клапан EGR", "Датчик EGR"] },
  "P0401": { title: "Exhaust Gas Recirculation Flow Insufficient Detected", system: "Emission", danger: "средний", description: "Недостаточный поток выхлопных газов в системе EGR. Проблемы с выхлопом.", canDrive: true, urgency: "1 неделя", priceMin: 2500, priceMax: 7000, actions: ["Очистить клапан EGR", "Заменить датчик EGR"], parts: ["Клапан EGR", "Датчик EGR"] },
  "P0402": { title: "Exhaust Gas Recirculation Flow Excessive Detected", system: "Emission", danger: "средний", description: "Избыточный поток выхлопных газов. Повышенное содержание выхлопных газов.", canDrive: true, urgency: "1 неделя", priceMin: 2500, priceMax: 7000, actions: ["Очистить клапан EGR", "Проверить датчик"], parts: ["Клапан EGR", "Датчик EGR"] },
  "P0420": { title: "Catalyst System Efficiency Below Threshold", system: "Emission", danger: "средний", description: "Проблема с катализатором. Повышенный уровень вредных выбросов. Возможны подергивания при ускорении.", canDrive: true, urgency: "1 неделя", priceMin: 5000, priceMax: 20000, actions: ["Диагностика датчиков кислорода", "Очистка топливной системы", "Замена катализатора"], parts: ["Катализатор", "Датчик кислорода"] },
  "P0430": { title: "Catalyst System Efficiency Below Threshold Bank 2", system: "Emission", danger: "средний", description: "Катализатор на второй стороне неэффективен. Проблемы с выхлопом.", canDrive: true, urgency: "1 неделя", priceMin: 5000, priceMax: 20000, actions: ["Диагностика датчиков", "Замена катализатора"], parts: ["Катализатор", "Датчик кислорода"] },
  "P0440": { title: "Evaporative Emission Control System Malfunction", system: "Emission", danger: "низкий", description: "Проблема с системой улавливания паров топлива. Может быть запах бензина.", canDrive: true, urgency: "1 месяц", priceMin: 1500, priceMax: 4000, actions: ["Проверить топливный бак", "Проверить датчик давления", "Диагностика"], parts: ["Угольный фильтр", "Датчик давления", "Шланги"] },
  "P0442": { title: "Evaporative Emission Control System Leak Detected", system: "Emission", danger: "низкий", description: "Утечка в системе EVAP. Может быть запах бензина, но опасности мало.", canDrive: true, urgency: "1 месяц", priceMin: 1000, priceMax: 3000, actions: ["Проверить угольный фильтр", "Проверить шланги", "Затянуть крышку топливного бака"], parts: ["Угольный фильтр", "Шланги EVAP", "Крышка топливного бака"] },
  "P0455": { title: "Evaporative Emission System Leak Detected (Large)", system: "Emission", danger: "низкий", description: "Большая утечка в системе EVAP. Явный запах бензина.", canDrive: true, urgency: "1 месяц", priceMin: 1500, priceMax: 4000, actions: ["Проверить крышку топливного бака", "Заменить угольный фильтр", "Проверить все шланги"], parts: ["Крышка топливного бака", "Угольный фильтр", "Шланги"] },
  "P0500": { title: "Vehicle Speed Sensor Malfunction", system: "Transmission", danger: "средний", description: "Датчик скорости не работает. Спидометр может не показывать скорость, проблемы с трансмиссией.", canDrive: true, urgency: "1 неделя", priceMin: 1500, priceMax: 4000, actions: ["Проверить датчик ABS", "Проверить проводку", "Заменить датчик"], parts: ["Датчик скорости / датчик ABS", "Провода"] },
  "P0501": { title: "Vehicle Speed Sensor Range Performance", system: "Transmission", danger: "средний", description: "Датчик скорости показывает нереальные значения. Проблемы с круиз-контролем.", canDrive: true, urgency: "1 неделя", priceMin: 1500, priceMax: 4000, actions: ["Проверить датчик", "Проверить проводку"], parts: ["Датчик скорости", "Провода и разъёмы"] },
  "P0505": { title: "Idle Air Control System Malfunction", system: "Engine", danger: "средний", description: "Нестабильный холостой ход. Двигатель может глохнуть на светофоре.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить дроссель", "Очистить инжектор", "Проверить датчик положения дроссельной заслонки"], parts: ["Дроссельная заслонка", "Форсунка инжектора", "Датчик TPS"] },
  "P0506": { title: "Idle Air Control System RPM Lower Than Expected", system: "Engine", danger: "средний", description: "Холостой ход слишком низкий. Двигатель может заглохнуть.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить дроссель", "Проверить подсос воздуха", "Проверить вакуумные шланги"], parts: ["Дроссельная заслонка", "Вакуумные шланги"] },
  "P0507": { title: "Idle Air Control System RPM Higher Than Expected", system: "Engine", danger: "средний", description: "Холостой ход слишком высокий. Двигатель работает на повышенных оборотах.", canDrive: true, urgency: "3 дня", priceMin: 1500, priceMax: 4000, actions: ["Очистить дроссель", "Проверить датчик температуры", "Проверить вакуумные шланги"], parts: ["Дроссельная заслонка", "Датчик температуры охлаждающей жидкости"] },
  "P0600": { title: "Serial Communication Link Error", system: "Computer", danger: "средний", description: "Ошибка связи между ЭБУ и другими блоками управления. Может привести к неправильной работе различных систем.", canDrive: true, urgency: "1 неделя", priceMin: 2000, priceMax: 6000, actions: ["Проверить разъёмы ЭБУ", "Перезагрузить ЭБУ", "Диагностика"], parts: ["Провода и разъёмы", "ЭБУ"] },
  "P0605": { title: "PCM Read Only Memory Error", system: "Computer", danger: "высокий", description: "Ошибка в памяти ЭБУ. Двигатель может не работать как надо или вообще не запуститься.", canDrive: false, urgency: "сегодня", priceMin: 3000, priceMax: 10000, actions: ["Перезагрузить ЭБУ", "Заменить ЭБУ", "Диагностика"], parts: ["ЭБУ (PCM)"] },
  "P0650": { title: "Malfunction Indicator Lamp Control Circuit", system: "Computer", danger: "низкий", description: "Проблема с лампочкой Check Engine. Может не светиться, но другие коды все равно записаны.", canDrive: true, urgency: "1 месяц", priceMin: 500, priceMax: 1500, actions: ["Проверить лампочку", "Проверить разъём", "Проверить предохранитель"], parts: ["Лампочка", "Предохранитель", "Провода"] },
  "P0700": { title: "Transmission Control System Malfunction", system: "Transmission", danger: "высокий", description: "Проблема с системой управления коробкой передач. Может быть невозможно переключать передачи.", canDrive: false, urgency: "сегодня", priceMin: 5000, priceMax: 15000, actions: ["Диагностика трансмиссии", "Заменить масло", "Проверить датчики"], parts: ["Масло трансмиссионное", "Датчики трансмиссии"] },
  "P0705": { title: "Transmission Range Sensor Circuit", system: "Transmission", danger: "высокий", description: "Датчик положения рычага коробки не работает. Коробка может не переключаться.", canDrive: false, urgency: "сегодня", priceMin: 2000, priceMax: 6000, actions: ["Проверить датчик Park/Neutral", "Проверить разъём", "Заменить датчик"], parts: ["Датчик положения рычага", "Провода"] },
  "P0710": { title: "Transmission Fluid Temperature Sensor Circuit", system: "Transmission", danger: "средний", description: "Датчик температуры масла трансмиссии не работает. Трансмиссия может перегреваться.", canDrive: true, urgency: "1 неделя", priceMin: 1500, priceMax: 4000, actions: ["Проверить датчик", "Заменить датчик", "Проверить уровень масла"], parts: ["Датчик температуры трансмиссии"] },
  "P0715": { title: "Input Shaft Speed Sensor Circuit", system: "Transmission", danger: "средний", description: "Датчик скорости входного вала не работает. Проблемы с переключением передач.", canDrive: true, urgency: "1 неделя", priceMin: 2000, priceMax: 5000, actions: ["Проверить датчик", "Проверить разъём", "Заменить датчик"], parts: ["Датчик входного вала", "Провода"] },
  "P0720": { title: "Output Shaft Speed Sensor Circuit", system: "Transmission", danger: "средний", description: "Датчик скорости выходного вала не работает. Проблемы с переключением.", canDrive: true, urgency: "1 неделя", priceMin: 2000, priceMax: 5000, actions: ["Проверить датчик", "Проверить разъём"], parts: ["Датчик выходного вала"] },
  "P0740": { title: "Torque Converter Clutch Circuit", system: "Transmission", danger: "средний", description: "Проблема с муфтой гидротрансформатора. Повышенный расход топлива, перегрев трансмиссии.", canDrive: true, urgency: "1 неделя", priceMin: 3000, priceMax: 8000, actions: ["Проверить масло", "Диагностика", "Заменить масло"], parts: ["Масло трансмиссионное", "Гидротрансформатор"] },
  "P0750": { title: "Shift Solenoid A Circuit", system: "Transmission", danger: "высокий", description: "Соленоид переключения передач не работает. Коробка не переключается на правильные передачи.", canDrive: false, urgency: "сегодня", priceMin: 2000, priceMax: 6000, actions: ["Проверить электрический разъём", "Заменить соленоид", "Диагностика"], parts: ["Соленоид переключения", "Провода"] },
  "P0755": { title: "Shift Solenoid B Circuit", system: "Transmission", danger: "высокий", description: "Второй соленоид не работает. Проблемы с переключением.", canDrive: false, urgency: "сегодня", priceMin: 2000, priceMax: 6000, actions: ["Заменить соленоид", "Проверить разъём"], parts: ["Соленоид переключения"] },
  "P0800": { title: "Transmission Control System Malfunction", system: "Transmission", danger: "высокий", description: "Серьёзная ошибка системы управления КПП. Может быть режим аварийного переключения.", canDrive: false, urgency: "сегодня", priceMin: 5000, priceMax: 15000, actions: ["Диагностика", "Перезагрузка ЭБУ трансмиссии", "Замена ЭБУ"], parts: ["ЭБУ трансмиссии"] },
  "P0801": { title: "Reverse Inhibit Control Circuit", system: "Transmission", danger: "средний", description: "Проблема с системой блокировки задней передачи. Задняя передача может работать некорректно.", canDrive: true, urgency: "1 неделя", priceMin: 1500, priceMax: 4000, actions: ["Проверить датчик", "Проверить разъём", "Диагностика"], parts: ["Датчик", "Провода"] },
  "P0840": { title: "Transmission Fluid Pressure Sensor Circuit", system: "Transmission", danger: "средний", description: "Датчик давления масла трансмиссии неисправен. Проблемы с переключением.", canDrive: true, urgency: "1 неделя", priceMin: 1500, priceMax: 4000, actions: ["Проверить датчик", "Заменить датчик"], parts: ["Датчик давления масла трансмиссии"] },
  "P0900": { title: "Clutch Actuator Circuit", system: "Transmission", danger: "высокий", description: "Проблема с актуатором сцепления (робот). Сцепление может не переключаться.", canDrive: false, urgency: "сегодня", priceMin: 4000, priceMax: 12000, actions: ["Проверить гидравлику сцепления", "Диагностика", "Замена актуатора"], parts: ["Актуатор сцепления", "Гидравлическая жидкость"] },
  "P1000": { title: "OBD System Self-Test Not Ready", system: "Computer", danger: "низкий", description: "Система не готова к тестированию. Коды могут быть фальшивыми. Проедьтесь несколько км.", canDrive: true, urgency: "1 месяц", priceMin: 0, priceMax: 0, actions: ["Проедьтесь 50-100 км", "Повторьте диагностику"], parts: [] },
  "P1101": { title: "Mass Air Flow Sensor Intermittent", system: "Engine", danger: "низкий", description: "Датчик MAF работает нестабильно (перебивается). Может быть временная ошибка.", canDrive: true, urgency: "1 месяц", priceMin: 500, priceMax: 2000, actions: ["Очистить датчик", "Проверить разъём", "Проверить воздухозаборник"], parts: ["Датчик MAF", "Воздушный фильтр"] },
};

export const OBD_STATS = {
  total: Object.keys(OBD_DATABASE).length,
  bySeverity: {
    низкий: Object.values(OBD_DATABASE).filter(x => x.danger === "низкий").length,
    средний: Object.values(OBD_DATABASE).filter(x => x.danger === "средний").length,
    высокий: Object.values(OBD_DATABASE).filter(x => x.danger === "высокий").length,
  },
  bySystem: {},
};

// Подсчитаем коды по системам
Object.values(OBD_DATABASE).forEach(code => {
  OBD_STATS.bySystem[code.system] = (OBD_STATS.bySystem[code.system] || 0) + 1;
});

export function lookupOBD(codeOrQuery) {
  const query = codeOrQuery.toUpperCase().replace(/[^A-Z0-9]/g, "");

  // 1. Точный поиск по коду
  if (OBD_DATABASE[query]) {
    return {
      code: query,
      exact: true,
      ...OBD_DATABASE[query],
    };
  }

  // 2. Частичный поиск по коду
  for (const code in OBD_DATABASE) {
    if (code.includes(query)) {
      return {
        code,
        exact: false,
        ...OBD_DATABASE[code],
      };
    }
  }

  // 3. Поиск по названию
  for (const [code, data] of Object.entries(OBD_DATABASE)) {
    if (data.title.toUpperCase().includes(query)) {
      return {
        code,
        exact: false,
        ...data,
      };
    }
  }

  return null;
}
